### ISSUE TITLE
client.Connect() hangs if unable to connect to SiriDB

### ISSUE THREAD

**Issue by Thrasd** [transceptor-technology/go-siridb-connector#1]
If I run the following code, without any SiriDB running, it will hang on the `client.Connect()` method. 
```
package main

import (
	"fmt"
	"github.com/transceptor-technology/go-siridb-connector"
)

func main() {
	channel := make(chan string)

	client := siridb.NewClient("iris",
		"siri",
		"brume", 
                [][]interface{}{
			{"localhost", 14000},
		}, channel)
	
	client.Connect()
	
	value, err := client.Query("list series", 10)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(value)

	//client.Close()
}
```
There is no example code, so this is just an assumption that this is the correct way to do it.
Also if I have a SiriDB running and connect to it, calling `client.Close()` will make the program hang.

For the `client.Connect()` issue, I have made [a fork](https://github.com/Thrasd/go-siridb-connector/commit/a35dd747c68181ad6592b20aed0f0e3a97924acb) and added a timeout in the `Connect` method (as a workaround for my usecase right now), but I assume you have another way of doing this, as there is no timeout parameter in the python library.

**Comment by joente** [comment]
Sorry for the lack of documentation. I will try to add some example code as soon as possible.

**Comment by joente** [comment]
I've updated the documentation and added some examples. Your code should have worked but it might be a problem that the client was not connected and some logging was send to the `channel`. Note that this `channel` is not required and if `nil` is used instead, the output will be send to the standard output. 

With `client.IsConnected()` you can test for having at least one connection.  

For your purpose it might be easier to use a single connection. 

The main difference between a client and a connection is that a Client has some auto-reconnect functionality and can be used with multiple connections. This way you can set-up a siridb database with a client which is basically never offline. Our Oversight database for example, runs on 6 siridb servers in 3 pools. When upgrading, we bring down one server in each pool, upgrade, and when back online we upgrade the other 3 servers. This way all clients stay connected to the database with at least 3 connections. A normal shutdown of siridb will finish all open inserts and queries before shutting down. New queries or inserts are not accepted and a server error will be returned. The `Client` acts on this server error and will try another connection.

**Comment by Thrasd** [comment]
Setting the `channel` to `nil` solved the problems, and everything is now working as expected. And thank you for the documentation.

However it is probably still a bug that it does not work if we provide a `channel`.

**Comment by joente** [comment]
My thought was that supplying a channel for logging would be easy for implementing custom log handling. The Go language is quite new for me so maybe there are better ways to implement this. 

I think that if you listen to the log channel it should work. For example:
```go
func printLogs(logCh chan string) {
	for {
		msg := <-logCh
		fmt.Printf("Log: %s\n", msg)
	}
}
```
And create the log channel like this:
```go
logCh := make(chan string)
go printLogs(logCh)
// now you can use the channel as log channel for the siridb Client
```

**Comment by Thrasd** [comment]
The Go language is also new for me, so the way you are doing it is most likely correct. An idea could be to add this example to the documentation, then people new to Go will at least be able to see how to use it.

**Comment by joente** [comment]
Thank you for your feedback, I've added a *Logging* section to the documentation.
