### ISSUE TITLE
insert example required

### ISSUE THREAD

**Issue by lilvinz** [transceptor-technology/go-siridb-connector#3]
I can't get insertion of points work as the documentation is basically void in this regard.

After lots of research i figured that data should be transferred in the following qpack pseudocode:
https://github.com/SiriDB/libsiridb/blob/master/src/pkg.c#L83
```
map(
    series_name,
    array(
        array(
            timestamp, value,
            timestamp, value,
            timestamp, value,
            timestamp, value,
       )
    ),
    series_name,
    array(
        array(
            timestamp, value,
            timestamp, value,
            timestamp, value,
            timestamp, value,
       )
    )
)
```
However it is still unclear to me how to construct this qpack sequence using golang.
My understanding is something like:
```
type SiriPoint struct {
	Ts    int64
	Value float64
}

type SiriSeries struct {
	Name   string
	Points []SiriPoint
}

seriesMap := make(map[string][]SiriPoint)

Insert(seriesMap, uint16(writeTimeout))
```

But this seems to result in a different qpack sequence as structs are involved and thus throws "Expecting a series to have at least one point." error.

Can you please advise or add a sample inserting a couple of points into a couple of series to make this clear?

Thanks in advance!

**Comment by lilvinz** [comment]
Ok, i figured it out:
```
seriesMap := make(map[string][][]interface{})

seriesMap["test"] = append(seriesMap["test"], []interface{}{timestamp, value})

Insert(seriesMap, uint16(writeTimeout))
```

**Comment by joente** [comment]
@AnjaBruls added a simple `create database` and `insert` example to the [README.md](https://github.com/SiriDB/go-siridb-connector/blob/master/README.md)
